version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/python:3.8.5
      - image: circleci/postgres:13.1
        environment:
          POSTGRES_USER: postgres 
          POSTGRES_PASSWORD: postgres 
          POSTGRES_DB: django-gatsby 
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: 
          name: "Run tests"
          command: |
            . venv/bin/activate
            python manage.py test

workflows:
  main:
    jobs:
      - tests